---
title: "unifrac"
author: "Vicki Hertzberg"
date: "4/24/2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Calculate unifrac distances

```{r}
library(phyloseq)

library(DECIPHER)
seqs <- getSequences(st)

# This next command will allow propagation of sequence names to the tip labels of the tree
names(seqs) <- seqs
alignment <- AlignSeqs(DNAStringSet(seqs), anchor=NA)

library(phangorn)

# Construct the tree
phang.align <- phyDat(as(alignment, "matrix"), type="DNA")
dm <- dist.ml(phang.align)
treeNJ <- NJ(dm) # Tip order will not equal sequence order
fit <- pml(treeNJ, data=phang.align)

## negative edges length changed to 0.

fitGTR <- update(fit, k=4, inv=0.2)
fitGTR <- optim.pml(fitGTR, model="GTR", optInv=TRUE, optGamma=TRUE, 
                    rearrangement = "stochastic", control=pml.control(trace=0))
detach("package:phangorn", unload=TRUE)

ps <- phyloseq(tax_table(tax),
               sample_data(samdf),
               otu_table(st, taxa_are_rows = FALSE),
               phy_tree( tGTR$tree))


plot_tree(ps, color="group", label.tips = "Genus", size = "abundance", plot.margin = 0.5, ladderize = TRUE)


```

